name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: Build with Gradle
      run: ./gradlew shadowJar
    - name: Publish artifact
      uses: actions/upload-artifact@v3
      with:
        name: FlectoneTwitchBot
        path: target
